run-name: Backfill

on:
  workflow_dispatch:
    inputs:
      year:
        description: 'Year'     
        required: true
        default: 2013

jobs:
  Backfill:
    name: Backfill
    runs-on: ubuntu-latest

    strategy:
      matrix:
        max_games: [100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380]

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Get data
        run: |
          mkdir data
          cd data
          git clone -n --depth=1 --filter=tree:0 https://github.com/IgorMichels/BrazilianSoccerData.git
          cd BrazilianSoccerData
          git sparse-checkout set --no-cone results/processed
          git checkout
                
      - name: Run backfill
        run: |
          cd Modeling/
          python backfill.py -y=${{ github.event.inputs.year }} -g=${{ matrix.max_games }} -m=${{ secrets.MAIL }} -p=${{ secrets.PASSWORD }}