run-name: Update

on:
  workflow_dispatch:

jobs:
  Update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3.2.0
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                
      - name: Run update
        run: |
          cd Modeling/
          python update_results.py -m=${{ secrets.MAIL }} -p=${{ secrets.PASSWORD }} -t=[BSM]
                
      - name: Commit changes
        run: |
          git add *
          git commit -m "Backfill"
          git push